SELECT Valutazione, Data
FROM VALUTAZIONE
WHERE CodFisc='C03' AND CodConteNuto=3
ORDER BY Data;

START TRANSACTION;
INSERT INTO UTENTE VALUES ('C11', 'Aaron', 'Audisio', 2021);
INSERT INTO VALUTAZIONE VALUES ('C11', 8 , '2021-3-10', 10);
COMMIT;